---
language: python
python:
  - "3.8"
branches:
  only:
    - main
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
services:
  - postgresql
env:
  - TEST_DB_URI=postgresql://james:whale@localhost/jameswhale
before_script:
  - psql -U postgres -c "create database jameswhale;"
  - psql -U postgres -c "CREATE USER james WITH PASSWORD 'whale';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE jameswhale TO james;"
  - psql -U james -d jameswhale -f ./build/database/jameswhale.sql
script:
  - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)
...
