version: '3.1'

services:
  website:
    build: ./
    restart: always
    ports:
    - 80:80
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: james
      POSTGRES_PASSWORD: whale
      POSTGRES_DB: jameswhale