---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  test:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install pylint

      - name: Run pylint
        run: pylint personal_website
        env:
          PY_COLORS: '1'
...